{% set name = "robust-laplacian" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robust_laplacian-{{ version }}.tar.gz
    sha256: a00d7c225e40b6f9a1b9c8de0c5cb51dadd35367e3fe61b265a4643165b4e08d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake <4
    - make  # [unix]
  host:
    - pip
    - python
    - scikit-build-core
  run:
    - python
    - numpy

test:
  imports:
    - robust_laplacian
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/nmwsharp/robust-laplacians-py
  summary: Build high-quality Laplace matrices on meshes and point clouds in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
