{% set name = "robust-laplacian" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robust_laplacian-{{ version }}.tar.gz
    sha256: 1db9eeb1a7aa340c3da902b125d2f58c7138feda206a72c2402dd25e702290d2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake <4
    - make  # [unix]
  host:
    - pip
    - python
    - scikit-build-core
  run:
    - python
    - numpy

test:
  imports:
    - robust_laplacian
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/nmwsharp/robust-laplacians-py
  summary: Build high-quality Laplace matrices on meshes and point clouds in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
